In [65]:
# Initialize Otter
import otter
grader = otter.Notebook("QUIZ02.ipynb")

# Quiz02-Machine Learning

In [66]:
import pandas as pd
import numpy as np

In [67]:
# Load data
 # start by loading the data
dataQ1 = pd.read_csv("Data1.txt", header = None, 
names = ["Exam 1 Score", "Exam 2 Score", "Accepted"])
 # initialize some useful variables
m = len(dataQ1["Accepted"])
x0 = np.ones(m)
size = np.array((dataQ1["Exam 1 Score"]))
bedrooms = np.array((dataQ1["Exam 2 Score"]))
XQ1 = np.array([x0, size, bedrooms]).T
yQ1 = np.array(dataQ1["Accepted"])
print(XQ1[:5])
print(yQ1[:5])

[[ 1.      6.1101 17.592 ]
 [ 1.      5.5277  9.1302]
 [ 1.      8.5186 13.662 ]
 [ 1.      7.0032 11.854 ]
 [ 1.      5.8598  6.8233]]
[nan nan nan nan nan]


# Logistic Regression in Python.
<hr style="border: 5px solid #003262;" />
<hr style="border: 1px solid #fdb515;" />

## Logistic Regression

---
Logistic regression is predicting in which category a given data point is. In binary classifiction, there are only two categories:

$$y \in \{0,1\}$$

In this question, you will implement logistic regression and apply it to two different datasets.
### Sigmoid
The sigmoid function, or logistic function, is a function that asymptotes at 0 and 1. The value at 0 is $\frac{1}{2}$.

$h_\theta(x) = g(\theta^Tx) = g(z) = \frac{1}{1+ e^{-z}} = \frac{1}{1+ e^{-\theta^Tx}}$

We are going to use the sigmoid function to predict how likely it is that a given data point is in category 0. Our hypothesis:

$h_\theta(x) = P(y = 0|x;\theta)$

Because there are only two categories (in this case), we can derrive that:

$P(y = 0|x;\theta) + P(y = 1|x;\theta)= 1$


#### The cost function

The cost function in logistic regression differs from the one used in linear regression. The cost function in logistic regression:

$$J(\theta) = - \begin{bmatrix}\frac{1}{m}\displaystyle\sum_{i=1}^{m}-y^{(i)}\log h(x^{(i)}-(1-y^{(i)})\log(1-h_\theta(x^{(i)}))\end{bmatrix}$$

Assume our hypothesis for an example is wrong, the higher probability $h_\theta$ had predicted, the higher the penatly.

A vectorized version of the cost function:

$$J(\theta) = \frac{1}{m} ⋅(−y^T \log(h)−(1−y)^T \log(1−h))$$

#### The gradient

The gradient is the step a minimization algorithm, like gradient descent, takes to get to the (local) minimum. Note that this step can be taken in a higher dimension and hence the gradient is a vector. This time, we are going to use an algorithm called conjugate gradient to find the minimum. How that algorithm works is beyond the scope if this course. If you are interested, you can learn more about it [here](https://en.wikipedia.org/wiki/Conjugate_gradient_method).

The partial derrivative or $J(\theta)$, i.e., Gradient:

$$\frac{\delta}{\delta\theta_J} = {\nabla_{\theta} J(\theta)} = \frac{1}{m}\displaystyle\sum_{i = 1}^{m} \begin{bmatrix}(h_\theta(x^{(i)}) - y^{(i)}\end{bmatrix}x_j^{(i)}$$

Vectorized from of Gradient:

$$\frac{\delta}{\delta\theta_J} = {\nabla_{\theta} J(\theta)} = \frac{1}{m} \cdot X^T \cdot (g(X\cdot\theta)-\vec{y})$$

# Question 1: Implement the function of Logistic Regression that would return cost and gradient.

In [68]:


def logistic_regression_cost_and_gradient(theta, X, y):
   
    m = y.shape[0]
    h = sigmoid(X @ theta)
    h = np.clip(h, 1e-8, 1 - 1e-8)
    # cost
    J = (1 / m) * (-y.T @ np.log(h) - (1 - y).T @ np.log(1 - h))

    # gradient
    grad = (1 / m) * (X.T @ (h - y))

    return J, grad

In [69]:
initial_theta = np.zeros(XQ1.shape[1])
cost, gradient = logistic_regression_cost_and_gradient(initial_theta, XQ1, yQ1)
print(cost)
print(gradient)

nan
[nan nan nan]


In [70]:
grader.check("q1")

q1 results: All test cases passed!

# Newton's method for logistic regression

Newton's method addresses getting to $f(\theta) = 0$, and minimizing $J(\theta)$ means getting $\frac{\partial J}{\partial \theta}$ to 0. There after applying Newton's method, extending it to multidimensional setting (Newton-Raphson method), the update rule becomes:

\begin{align*}
\theta &:= \theta - \frac{\partial J(\theta) / \partial \theta} {H} \\
       &:= \theta - \frac{\nabla_{\theta} J(\theta)} {H} \\
       &:= \theta - H^{-1} \nabla_{\theta} J(\theta)
\end{align*}

${\nabla_{\theta} J(\theta)}$ is defined in the question 1, and $H$ is the Hessian matrix, given as:

$$
H_{ij} = \frac{1}{m} \sum_{k=1}^{m} g(z^{(k)})\big(1 - g(z^{(k)})\big) x_i^{(k)} x_j^{(k)}
$$

# Question 2: Implement the function to create a Hessian Matrix.

In [71]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def compute_hessian(X, theta):
  
    m = X.shape[0]
    h = sigmoid(X @ theta)
    #diagonal
    R = np.diag((h * (1 - h)).flatten())
    # Hessian
    H = (1 / m) * (X.T @ R @ X)

    return H

In [72]:
theta = np.zeros((X.shape[1], 1))
H = compute_hessian(X, theta)

In [73]:
H

array([[ 2.50000000e-01,  1.36947271e-02,  4.57753898e-02,
         6.18938338e-02, -6.36796007e-03,  7.53424034e-02,
         1.49583323e-02,  7.67038337e-03,  3.87062793e-03,
         3.55875032e-02,  3.06346073e-02, -1.31275953e-03,
         1.26082186e-02, -2.76204706e-03,  4.27746262e-02,
         1.29912680e-02,  2.95294996e-03,  2.35802361e-03,
         4.56945212e-03,  1.02227103e-03,  2.89274082e-02,
         1.95927957e-02, -1.75695667e-04,  4.73335083e-03,
        -4.26239309e-04,  5.64792459e-03, -1.57545194e-03,
         3.14314006e-02],
       [ 1.36947271e-02,  6.18938338e-02, -6.36796007e-03,
         1.49583323e-02,  7.67038337e-03,  3.87062793e-03,
         3.06346073e-02, -1.31275953e-03,  1.26082186e-02,
        -2.76204706e-03,  1.29912680e-02,  2.95294996e-03,
         2.35802361e-03,  4.56945212e-03,  1.02227103e-03,
         1.95927957e-02, -1.75695667e-04,  4.73335083e-03,
        -4.26239309e-04,  5.64792459e-03, -1.57545194e-03,
         1.14603386e-02,  1.58

In [74]:
grader.check("q2")

q2 results: All test cases passed!

## Regularized linear regression

---
Regularization is a meganism for preventing overfitting. _Overfitting_ means that our model works extremely well on the training set but bad in the real world. It's focussed on the training data. _Underfitting_ is either a not well trained model or the feature mapping is not done (correctly). We will use regularization in this exercise. Furtermore, we are going to look at a more complex decision boundary

In this part of the exercise, you will implement regularized logistic regression to predict whether microchips from a fabrication plant passes quality assur- ance (QA). During QA, each microchip goes through various tests to ensure it is functioning correctly.

Suppose you are the product manager of the factory and you have the test results for some microchips on two different tests. From these two tests, you would like to determine whether the microchips should be accepted or rejected. To help you make the decision, you have a dataset of test results on past microchips, from which you can build a logistic regression model.

In [75]:
# start by loading the data
data = pd.read_csv("Data2.txt", header = None, 
                   names = ["Test 1", "Test 2", "Status"])

# initialize some useful variables
m = len(data["Status"])
size = np.array((data["Test 1"]))
bedrooms = np.array((data["Test 2"]))
X = np.array([size, bedrooms]).T # don't add a column of ones yet.
y = np.array(data["Status"])

X[:5]

array([[ 0.051267,  0.69956 ],
       [-0.092742,  0.68494 ],
       [-0.21371 ,  0.69225 ],
       [-0.375   ,  0.50219 ],
       [-0.51325 ,  0.46564 ]])

### Feature Mapping

One way to fit the data better is to create more features from each data point. While the feature mapping allows us to build a more expressive classifier, it also more susceptible to overfitting. This will also add $x_0$.

In [76]:
def map_feature(X1, X2, degree):
    if not type(X1) == np.ndarray:
        X1 = np.array([X1])

    if not type(X2) == np.ndarray:
        X2 = np.array([X2])

    assert X1.shape == X2.shape
    
    out = np.ones((len(X1), 1))
    for i in range(1, degree+1):
        for j in range(i + 1):
            new = (X1 ** (i-j) * X2 ** j).reshape(len(X1), 1)
            out = np.hstack((out, new))
    return out

X = map_feature(X[:,0], X[:,1], degree=6)

### Computing Cost
#### Cost function
Regularization works by penalizing theta. Theta values can be high when an overfit occurs so we prefer to keep them low. $\lambda$ is the regularization parameter. If $\lambda=0$, no regularization happens. If $\lambda$ is some big number, $\theta$ has a very high penalty. Just like the learning rate $\alpha$ you have to try out certain values and see which work.

The cost function with regularization:

$$J(\theta) = \frac{1}{m}\displaystyle\sum_{i=1}^{m}-\begin{bmatrix}y^{(i)}\log h(x^{(i)}+(1-y^{(i)}\log(1-h_\theta(x^{(i)})) \end{bmatrix} + \frac{\lambda}{m}\displaystyle\sum_{j=1}^{n}{\theta_j}^2$$

# Question 3: Implement the function of Regularized Logistic Regression cost.

In [79]:
def regularized_logistic_regression_cost(theta, X, y, lambda_):
    """
    Compute the regularized cost and gradient for logistic regression.

    Parameters:
    - theta: Parameters of the model (n x 1 or n, )
    - X: Feature matrix (m x n)
    - y: Labels (m x 1 or m, )
    - lambda_: Regularization parameter (scalar)

    Returns:
    - J: Regularized cost (scalar)
    - reg_term: Regularized term (scalar)
    """
    # number of training samples
    m = len(y)

    z = np.dot(X, theta)
    h = (1 / (1 + np.exp(-z)))
    h = np.clip(h, 1e-8, 1 - 1e-8)
    cost =  (-1/m) * ((y @ np.log(h) + (1 - y) @ np.log(1 - h)))
    reg_term = (lambda_ / (2 * m)) * np.sum(np.square(theta[1:]))
    
    return cost, reg_term

In [80]:
grader.check("q3")

q3 results: All test cases passed!

#### Regularized Gradient descent
Gradient descent, just like the cost function, is slightly modified for regularization.

For $\theta_{j}$ where $j = 0$: 

$$\theta_j := \theta_j -\alpha \begin{bmatrix}\frac{1}{m}\displaystyle\sum_{i=1}^{m}(h_\theta(x^{(i)}-y^{(i)}){x_0}^{(i)}\end{bmatrix}$$

For $\theta_{j}$ where $j \in \{1, 2, ..., n\} $: 

$$\theta_j := \theta_j -\alpha \begin{bmatrix}\frac{1}{m}\displaystyle\sum_{i=1}^{m}(h_\theta(x^{(i)}-y^{(i)})x_j^{(i)} + \frac{\lambda}{m}{\theta_j} \end{bmatrix}$$

Note that we don't penalize our bias vector $X_1$.

# Question 4: Implement the function of Regularized Logistic Regression gradient.

In [81]:
def regularized_gradient_descent(X, y, theta, alpha, lambda_, num_iters):
    m = len(y)

    for i in range(num_iters):
        z = np.dot(X, theta)
        h = (1 / (1 + np.exp(-z)))

        error = h - y  # shape: (m,)
        grad = (1 / m) * np.dot(X.T, error)  # shape: (n,)

        # Regularize all theta except theta[0]
        reg_term = (lambda_ / m) * theta
        reg_term[0] = 0  # Do not regularize the bias term

        grad += reg_term

        # Update theta
        theta -= alpha * grad

    return theta

In [82]:
grader.check("q4")

q4 results: All test cases passed!